### ISSUE TITLE
-segment-timeline cause 404 

### ISSUE THREAD

**Issue by DanielMartine** [gpac/gpac#1013]
Hello everyone, testing my live manifest on ITEC validator I receive a warning:

> If more than one Media Segment is present the duration attribute or SegmentTimeline element shall be present.

By adding `-segment-timeline` on my MP4Box command:

`MP4Box -dash-live 8000 -subdur 8000 -bound -profile dashavc264:live -mpd-refresh 3600.0 -time-shift 24 -min-buffer 4000 -insert-utc -no-cache -segment-timeline -out manifest.mpd 1080set.mp4#video 720set.mp4#video 360set.mp4#video 1080set.mp4#audio 720set.mp4#audio 360set.mp4#audio`

I get the following error at the start of the process and it's impossible to display the streaming:

> [DASH] Drift between minCTS of segment and MPD start time is 0.0209375 s

Cheking PTS of my input video file i get:

0.021016
2.021016
4.021016
6.021016
8.021016
[...]

I notice a delay at start that i think could be the issue.
What do you think about, may be due to PTS delay?
I have to correct my encoding or it can be considered an issue of mp4box?
Thanks a lot!

**Comment by DanielMartine** [comment]
Finally i got a clean encode process with regular PTS, starting MP4box live dashify,
the following error message never happens again:

> [DASH] Drift between minCTS of segment and MPD start time is 0.0209375 s

however im already unable to display the live on video.js contrib dash if i add to my command line -segment-timeline

**Comment by chanof** [comment]
Same issue

**Comment by aureliendavid** [comment]
Hi, 

The drift message here is not an error and can be ignored. 

However I think we have two problems here: 

1. `-segment-timeline` is broken in general 
2. `-segment-timeline` doesn't work well with `-dash-live`

I think 1. can be fixed easily. It's the one that creates the 404s. I'm looking into it now and should post a fix soon. 

For 2., it looks like the timelines generated in a live context are wrong (I think they use the wrong timescale). I haven't found out why yet. 

I'll keep you posted of my progress.

**Comment by aureliendavid** [comment]
This should now be fixed. 

For the record: 

issue 1. came from a discrepancy between the filenames of the segments and the segmenttemplate published in the mpd

issue 2. came for the fact that we stored segment timestamps in dash timescale in the context but they should be written in media timescale in the timeline

@DanielMartine : for your command to work with -segment-timeline and -dash-live you need to lower the value of -mpd-refresh to something around the dash duration (so 8.0 in your example)

this is due to the fact that with a live timeline, the content of the mpd changes for each loop so you have to tell the player to reload it often

**Comment by DanielMartine** [comment]
hi @aureliendavid I have a closed gop every two seconds, I do not understand if both -dash-live and -subdur accept a multiple of the gop or if I have to set -dash-live to the length of the gop (2000)
Now on [www.allibrante.com ](www.allibrante.com) is running the original command with your -mpd-refresh time correction on the last branch: 445-g1f3ada0-master but on ITEC Validator I still get the error regarding the segment timeline:
May i ask a help tu understand what is going here?
Thanks!

> Start Schematron validation
> ===========================
> 
> <svrl:failed-assert test="if (not(@duration) and not(child::dash:SegmentTimeline)) then false() else true()"
> location="/*[local-name()='MPD' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']/*[local-name()='Period' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']/*[local-name()='AdaptationSet' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]/*[local-name()='Representation' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]/*[local-name()='SegmentTemplate' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']">
> <svrl:text>If more than one Media Segment is present the duration attribute or SegmentTimeline element shall be present.</svrl:text>
> </svrl:failed-assert>
> <svrl:failed-assert test="if (not(@duration) and not(child::dash:SegmentTimeline)) then false() else true()"
> location="/*[local-name()='MPD' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']/*[local-name()='Period' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']/*[local-name()='AdaptationSet' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]/*[local-name()='Representation' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][2]/*[local-name()='SegmentTemplate' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']">
> <svrl:text>If more than one Media Segment is present the duration attribute or SegmentTimeline element shall be present.</svrl:text>
> </svrl:failed-assert>
> <svrl:failed-assert test="if (not(@duration) and not(child::dash:SegmentTimeline)) then false() else true()"
> location="/*[local-name()='MPD' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']/*[local-name()='Period' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']/*[local-name()='AdaptationSet' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]/*[local-name()='Representation' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][3]/*[local-name()='SegmentTemplate' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']">
> <svrl:text>If more than one Media Segment is present the duration attribute or SegmentTimeline element shall be present.</svrl:text>
> </svrl:failed-assert>
> <svrl:failed-assert test="if (not(@duration) and not(child::dash:SegmentTimeline)) then false() else true()"
> location="/*[local-name()='MPD' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']/*[local-name()='Period' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']/*[local-name()='AdaptationSet' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][2]/*[local-name()='Representation' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][1]/*[local-name()='SegmentTemplate' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']">
> <svrl:text>If more than one Media Segment is present the duration attribute or SegmentTimeline element shall be present.</svrl:text>
> </svrl:failed-assert>
> <svrl:failed-assert test="if (not(@duration) and not(child::dash:SegmentTimeline)) then false() else true()"
> location="/*[local-name()='MPD' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']/*[local-name()='Period' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']/*[local-name()='AdaptationSet' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][2]/*[local-name()='Representation' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][2]/*[local-name()='SegmentTemplate' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']">
> <svrl:text>If more than one Media Segment is present the duration attribute or SegmentTimeline element shall be present.</svrl:text>
> </svrl:failed-assert>
> <svrl:failed-assert test="if (not(@duration) and not(child::dash:SegmentTimeline)) then false() else true()"
> location="/*[local-name()='MPD' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']/*[local-name()='Period' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']/*[local-name()='AdaptationSet' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][2]/*[local-name()='Representation' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011'][3]/*[local-name()='SegmentTemplate' and namespace-uri()='urn:mpeg:dash:schema:mpd:2011']">
> <svrl:text>If more than one Media Segment is present the duration attribute or SegmentTimeline element shall be present.</svrl:text>
> </svrl:failed-assert>

**Comment by aureliendavid** [comment]
well we disagree with the validator here

we write the timeline at the adaptationset level because it applies to all representations - each representation inherits the timeline of the set

the validator says that each representation should contain a timeline (which would be the same for all of them in our case), and we're not doing that

you can open a different issue for that but this will probably not be a priority

as for this issue, if the original problem is now fixed please close it and open separate issues it there are further problems

**Comment by rbouqueau** [comment]
@DanielMartine Please report to the validator team with a link this #1013 issue. Thank you.

**Comment by DanielMartine** [comment]
thanks for the great support guys, is already much more stable with these changes, can i ask for clarification: when you say "to something around the dash duration"
- you mean -dash-live time or -subdur time ?
- you say around, and i see that -mpd-refresh works better with some decimals more, to avoid asincronous delete i think, may i ask which is the right choise to be sure to avoid artifacts?

I will present the results to the ITEC team today
Thanks a lot!

**Comment by aureliendavid** [comment]
I don't have much insight about optimal dash parameters to be honest, I'm just looking at what the code does. In this case the mpd changes for each loop so it needs to be refreshed at least that often. The loop time depends on both -dash-live and -subdur time (mostly -dash-live). Trial & error is your best option here.

**Comment by timse7** [comment]
Did you check with http://dashif.org/conformance which is more up to date
