### ISSUE TITLE
GPAC 0.9.0 - roll grouping type in sgpd and sbgp boxes

### ISSUE THREAD

**Issue by BucherTomas** [gpac/gpac#1260]
I skipped GPAC 0.8.0 evaluation, so it might have been introduced there, but I see that GPAC 0.9.0 is newly paying closer attention to `sgpd` and `sbgp` box and info about roll distance, i.e. audio decoder delay. If grouping type is set to `roll` in those boxes, mp4box when dashing prints `[Dasher] WARNING! Max SAP type 4 detected - switching to FULL profile`.

Representation element for audio track in the mpd manifest then changes value to 4 for `startWithSAP` attribute and bigger issue is that the profile is truly set to full, which may cause possible incompatibility with some user agents, e.g. with TVs due to their strict implementations.

Mp4 content with an audio track muxed by FFmpeg is using these `sgpd` and `sbgp` boxes with grouping type set to `roll`, so you can imagine that upgrading to 0.9.0 as is would likely break many current workflows based on FFmpeg -> mp4box chain that rely for example on live profile in their dash streams and use the source mp4 without demuxing to raw bitstreams.

I uploaded a test file to your Mediafire share as roll_distance.mp4 that exhibits this when dashed.

I assume the specification is clear in this regard and the new behavior adheres to it, but is it truly that strict? Older GPAC versions have no issues with such content and the resulting dash stream is always correctly in sync between audio and video even if specifying desired live or onDemand profile.

Mp4 files missing `sgpd` and `sbgp` boxes altogether are not affected by this at all. Unlikely to do it without them in FFmpeg, though (remotely related to https://github.com/gpac/gpac/issues/1253 ) .

Thank you in advance for your comments.

**Comment by jeanlf** [comment]
that's a good point, I think we should (at least for now and most of known codecs) skip SAP evaluation on audio streams - I'll look at that as soon as I fix the windows path bug which is rather urgent :)

**Comment by jeanlf** [comment]
should now be fixed, strict sap mode for all streams can be reactivated using `strict_sap` option of dash muxer

**Comment by BucherTomas** [comment]
Thank you, but there's unfortunately no change with 0.9.0-DEV-rev2453-g1c0f601a-filters, dash muxer still switches to full profile with that roll_distance.mp4 I provided to you.

Since strict_sap is not recognized, it appears that the commit did not make it into the nightly build.

**Comment by jeanlf** [comment]
my bad, should be good now

**Comment by BucherTomas** [comment]
Thank you, profile now remains as live. Is it correct that `startWithSAP` is still 4 with this change?

**Comment by jeanlf** [comment]
It's not a bug for sure - we need to check if this breaks existing players/workflows, in which case I'll switch it back to 1. If you have any feedback on that please let us know

**Comment by BucherTomas** [comment]
I can't speak for every javascript web player out there, but I'd assume they would ignore it as does ExoPlayer on Android.
However, TV sets are another matter. HbbTV 2.0.1 supporting profile "urn:mpeg:dash:profile:isoff-live:2011" is dependent in some aspects on  https://www.etsi.org/deliver/etsi_ts/103200_103299/103285/01.02.01_60/ts_103285v010201p.pdf which requires `startWithSAP` as 1 or 2 as mentioned several times throughout the specification.
Please see paragraph 4.2.4  and specifically 6.2, which concerns audio for AAC family of codecs.

**Comment by jeanlf** [comment]
OK - DASH-IF validator seems happy with this but let's be cautious
The `strict_sap` option now lets you choose the behaviour: ignore (default), signal true SAP type but don't switch profile or warn and switch profile.

**Comment by Murmur** [comment]
This document `Dash_c065274_ISO_IEC_23009-1_2014.pdf` has a lot to say about startWithSAP values. I have never seen startWithSAP=4 being used in any commercial or opoensource dash packagers, first time I see it it's here. I tend to guess HbbTV may be very sensitive with `>=3` values. 

```
8.4: Profile "urn:mpeg:dash:profile:isoff-live:2011"
In addition, Representation elements contained in an AdaptationSet element complying to 
this profile shall have the following constraint
* Representation elements with @startWithSAP value (either supplied directly or inherited 
from the containing AdaptationSet) equal to 3 may be ignored if both the following 
conditions hold: 
- the containing Adaptation Set contains more than one Representation, and 
- no other Representation has the same value for @mediaStreamStructureId. 
* Representation elements with a @startWithSAP value (either supplied directly or inherited 
from the containing) absent, zero or greater than 3 may be ignored. 

A.6 Switching Representations 
If @segmentAlignment is set true and the @startWithSAP is set to 1, 2 or 3 (and in the 
latter case the Representation@mediaStreamStructureId is identical for the 
two Representations), then the client may switch at any Segment boundary by just 
concatenating Segments with consecutive indices from different Representations. 
No overlap downloading and decoding is required.
```

I would like to FFMPEG transcode audio streams without `sgpd,sbgp/roll)` atoms just for an extra sure but no success, it may be a mission impossible with ffmpeg(?).

**Comment by jeanlf** [comment]
you mean remove roll information?

**Comment by Murmur** [comment]
We have one very specific HbbTV television having dash problems, one reference stream works fine and it's using AAC audio without `sgpd,sbgp/roll` atoms. Everything else has a roll-group and playback fails. 

(maybe a total off-topic)
Problem may not actually relate to a roll value at all but we try to make everything init+seg+mpd as close as possible to that one reference stream to have a final explanation. I made a cruel test stream removing sgpd,sbgp atoms(+fix mdat trun.byteoffset). Firefox cannot playback audio but video ok (Chrome,IE dashsj is fine but lipsync sure may be changed), still doing various other "random" test use-cases to try run on that hbtv device.

**Comment by jeanlf** [comment]
just added `noroll`option to the isom muxer, you can try removing the sample group from your source files

**Comment by BucherTomas** [comment]
Thanks @jeanlf for the option.

Doesn't work with `gpac -i source.mp4 mp4mx:noroll @ -o output.mp4`, though. There's no output and no printed error.

It seems that `mp4mx` filter is not connecting properly, for example replacing `mp4mx:noroll` with `mp4dmx:alltk` works fine. The syntax I used is therefore hopefully ok.

I also wanted to see more information why it is failing by adding `-logs all@debug` before `-i`, but that fails with
>Failed to load filter all@debug: no such filter registry
Failed to load filter all@debug

Logs option is incorrectly(?) handled as a filter.

Btw. can mp4mx filter be used also in the same chain with dasher filter? E.g. `gpac -i source dasher:{opts} @ mp4mx:{opts} @ -o mpd`. Thank you.

**Comment by jeanlf** [comment]
Note that you shouldn't need to insert the muxer in the chain the rframer should be enough `gpac -i source reframer @ -o dst.mp4:noroll`
But it's strange that the muxer doesn't load using your command, I'll look at that
For logs, the syntax (at least for now) for all `gpac`options exept for sources/destination and help is `-name=value`, so here `-logs=filter@debug`

**Comment by jeanlf** [comment]
this should now be fixed, can you give it a try (and many thanks for testing all this!!)

I need to elaborate a bit more on my answer on your command `gpac -i source dasher:{opts} @ mp4mx:{opts} @ -o mpd`. This will likely fail as the first dasher output (MPD file) is instructed to connect to mp4mx which will fail. See `gpac -h links mp4mx`and `gpac `h links dasher`to view their connections. But like I said, `gpac -i source -o mpd:{opts}` will pass `:{opts}`to both dasher and mp4mx filters.

In the same way, `gpac -i source mp4mx:{opts} @ dasher:{opts} @ -o mpd` will fail because the mp4mx filter only accepts fout/pout/sockout as destinations. The reason is that the mp4mx filter does not declare an output mime type, preventing it from connecting to mp4dmx. This is done on purpose for the time being, as the demuxer requires a complete file in non-fragmented mode. This somehow relates to #644, we'll work on that in the future.

**Comment by BucherTomas** [comment]
Thank you for your help, both methods of using mp4mx filter (after source with mp4 output and with dasher options together after mpd output) are now working.

Hopefully one last question regarding the roll grouping type: If I use the `noroll` option, I see that `sbgp` box is now completely omitted as I'd assume it would, but `sgpd` with roll type is still present.  Is that expected?

**Comment by jeanlf** [comment]
it's normal behaviour for the current code yes - but I think we should remove it since no samplegroup maps to this group description

**Comment by jeanlf** [comment]
`sgpd` is now removed when using `noroll`

**Comment by Murmur** [comment]
By the way is it possible to give `noroll` argument to an older MP4Box binary file?

**Comment by jeanlf** [comment]
nope this is supported only in 0.9+

**Comment by Murmur** [comment]
Thanks my question was actually bad trying to ask `gpac.exe | MP4Box.exe`, I have this version from the master trunk but not sure if this is available in an old skool argument syntax.

```
MP4Box.exe
Not enough arguments - check usage with -h
MP4Box - GPAC version 1.0.0-rev204-g348365dd1-ab-suite
(c) 2000-2020 Telecom Paris distributed under LGPL v2.1+ - http://gpac.io

```

**Comment by jeanlf** [comment]
ha, ok - you can always pass filters arguments in a global way when they are not mapped in MP4Box:

`MP4Box [your args] --noroll=yes`

(order doesn't matter)
