### ISSUE TITLE
msvcr100.dll is no longer supplied by GPAC installers

### ISSUE THREAD

**Issue by heustess** [gpac/gpac#1300]
GPAC installers will no longer work (specifically Mp4Box from the command prompt) on a clean install of Windows 10 Home Version 1903 OS build 18362.295 because msvcr100.dll is no longer supplied by GPAC installers and is not included in a clean Windows install.
Perhaps you could include Microsoft Visual C++ 2010 Service Pack 1 Redistributable Package MFC Security Update (vcredist_x86.exe or vcredist_x64.exe) from https://www.microsoft.com/en-us/download/details.aspx?id=26999 to obtain msvcr100.dll like you supplied vc2015 to obtain vcruntime140.dll.

**Comment by aureliendavid** [comment]
you're right it's a problem, we shouldn't depend on msvcr100 at all anymore (that's why it's not in the installers), but some included dependencies (namely ssl and crypto) are still the ones built against vc10 

I'll replace them with vs2015 libs and regenerate the installers and update here 

thanks for the report

**Comment by aureliendavid** [comment]
should be fixed for the latest installers now

everything should now depend on vcruntime140.dll only which is included in the installer

(unfortunately in the meantime the certificate of our downloading server has expired so you might get a warning when trying to download until we get it renewed)

**Comment by douglasg14b** [comment]
This does not appear to be fixed, just ran mp4box and received the error:

> The code execution cannot proceed because MSVCR100.dll was not found. Reinstalling the program may fix this problem.

This occurs on 64bit Windows 10 Enterprise with the 64bit GPAC.

**Comment by aureliendavid** [comment]
what installer did you use?

**Comment by douglasg14b** [comment]
Windows 64 bit from https://gpac.wp.imt.fr/downloads/

I have reinstalled and the error persists.

**Comment by aureliendavid** [comment]
can you try with the latest from here: https://gpac.wp.imt.fr/downloads/gpac-nightly-builds/ ?

like this one https://download.tsi.telecom-paristech.fr/gpac/new_builds/win64/gpac-0.8.0-rev249-gba3f36c9-master-x64.exe

**Comment by douglasg14b** [comment]
That installer worked as expected.

Do any of the nightly builds have a signature? I'm probably going to have a tough time getting that installed in production without one...

**Comment by aureliendavid** [comment]
there's no portable exe but you can unpack the installer with 7zip and use it in place
