### ISSUE TITLE
Inserting udta box removes alternative brand

### ISSUE THREAD

**Issue by CoSoCo** [gpac/gpac#1453]
- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at http://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...).

I added an additional alternative brand with:
```
<?xml version="1.0" encoding="UTF-8" />
<GPACBOXES>

<Box path="ftyp+">
<BS fcc="ftyp"/>
<BS data="71742020200709007174202043414550"/>
</Box>

<Box path="ftyp">
</Box>

</GPACBOXES>
```
Result:
```
00 00 00 18 66 74 79 70 71 74 20 20 20 07 09 00 71 74 20 20 43 41 45 50 00 00 18 78 6D 6F 6F 76   ....ftypqt   ...qt  CAEP...xmoov
00 00 00 6C 6D 76 68 64 00 00 00 00 00 00 00 00 00 00 00 00 00 00 75 30 00 0D 51 B0 00 01 00 00   ...lmvhd..............u0..Q°....

```

After I added a udta box with:
```
<?xml version="1.0" encoding="UTF-8" />
<GPACBOXES>

<Box path="moov.mvhd-">
<BS fcc="udta"/>
<BS dataFile="MVI_1324.udta" dataOffset="8" dataLength="65588"/>
</Box>

</GPACBOXES>
```
Now in the result the alternative brand "CAEP" was deleted:
```
00 00 00 14 66 74 79 70 71 74 20 20 00 00 02 00 71 74 20 20 00 01 18 B4 6D 6F 6F 76 00 01 00 3C   ....ftypqt  ....qt  ...´moov...<
75 64 74 61 00 00 00 14 43 4E 43 56 43 61 6E 6F 6E 41 56 43 30 30 30 34 00 00 00 0C 43 4E 44 4D   udta....CNCVCanonAVC0004....CNDM
```

**Comment by jeanlf** [comment]
you cannot add a brand through patches.
More generally, with a boxpatch, you cannot modify anything inside a box, except adding or removing a child box. Any other modification to boxes must be done through official options.

In your case, use `-ab CAEP` to add a brand.

**Comment by CoSoCo** [comment]
This works fine:
```
$ MP4Box -ab CAEP -out MVI_1324_copy_CEAP2.mov MVI_1324_copy.mov
```
But the added brand is still removed again by:
```
$ MP4Box -patch MVI_1324_udta.xml -out MVI_1324_copy_CEAP2_udta.mov MVI_1324_copy_CEAP2.mov
```
So please reopen this issue!

Additionally I want to change the qt minor_version from 00 00 02 00 to 20 07 09 00. How is this possible?

**Comment by jeanlf** [comment]
I need to update the doc here: saving to .mov will perform cleanup of a few things in the input file, including resetting brands to only have "qt  " minor version 512.

You therefore must set your brand info whenever muxing to QT:

`MP4Box -patch MVI_1324_udta.xml -out MVI_1324_copy_CEAP_udta.mov MVI_1324_copy_CEAP.mov -ab "ABCD" `

You can set the major brand version using `-brand "qt  :1024"

I just pushed a fix in mp4box to allow using hexa value for minor version:
`-brand "qt  :0x20070900`

**Comment by CoSoCo** [comment]
Unfortunately this does not work with gpac_0.9.0-DEV-rev55-g98f819d1-filters_amd64.deb
```
$ MP4Box -brand "qt :0x20070900" -ab "CEAP" -patch MVI_1324_udta.xml MVI_1324_copy.mov -out MVI_1324_copy_CEAP_udta2.mov
```

I get:
```
00000000   00 00 00 1C 66 74 79 70 71 74 20 3A 00 00 00 00 71 74 20 20 71 74 20 3A 43 45 41 50 00 00 00 08   ....ftypqt :....qt  qt :CEAP....
00000032   77 69 64 65 00 01 18 B4 6D 6F 6F 76 00 01 00 3C 75 64 74 61 00 00 00 14 43 4E 43 56 43 61 6E 6F   wide...´moov...<udta....CNCVCano
```
But I want to get:
```
00000000   00 00 00 18 66 74 79 70 71 74 20 20 20 07 09 00 71 74 20 20 43 41 45 50 00 01 7F E8 6D 6F 6F 76   ....ftypqt   ...qt  CAEP...èmoov
00000032   00 01 00 3C 75 64 74 61 00 00 00 14 43 4E 43 56 43 61 6E 6F 6E 41 56 43 30 30 30 34 00 00 00 0C   ...<udta....CNCVCanonAVC0004....
```

**Comment by jeanlf** [comment]
you're missing a space in your brand definition, it should be `:qt  :0x20070900`, not `:qt :0x20070900` - brands must always be 4 characters

**Comment by CoSoCo** [comment]
Ah, thanks. But I still get an additional wide atom before the moov atom, which is not needed.

**Comment by jeanlf** [comment]
The `wide` box is not injected by GPAC, it must be in your source, you can remove it with boxpatch

**Comment by jeanlf** [comment]
The `wide` box is not injected by GPAC, it must be in your source, you can remove it with boxpatch
