### ISSUE TITLE
-splits is taking too much ram and time

### ISSUE THREAD

**Issue by megapro17** [gpac/gpac#1850]
I have 3.56 gb file. After entering `MP4Box -splits 2048000 1.mp4` it took 13 minutes and almost 4 gb of ram to do the operation. Video was stored in ramdisk. I think this option can be optimized because ffmpeg doesn't take this amount of resources when using `-ss -to` options.
Version is latest `MP4Box - GPAC version 1.1.0-DEV-rev1075-gda60a893-master`

**Comment by jeanlf** [comment]
Indeed, thanks for the report. The reframer was not flushing gops until the end point was known, hence a crazy memory usage. This should now be fixed, can you give it a try ?

Also note that by default MP4Box will use file interleave as storage mode which may slow down things and requires a temp file. You may want to use `-flat` or `-newfs` to speed things up.

**Comment by megapro17** [comment]
Amazing! After update it's taking only 1 minute to split! Default: 69 seconds, flat: 61, newfs: 59. File is progressive. 

By the way, there is old issue, with `-out` option when using `-splits`, and it's still not working... If you enter folder name it outputs error. If you enter not existing file, it just outputs whole file without splits
```
PS R:\> MP4Box -splits 100 -out R:\Out .\1.mp4
AVCC: invalid syntax for REXT profile, patching.
splitting: file 1 done
[Core] system failure for file opening of "R:\Out" in mode "w+b": 0x00000005
[FileOut] cannot open output file R:\Out
[FileOut] output file handle is not opened, discarding 9733 bytes
Split failed: I/O Error
```
https://sourceforge.net/p/gpac/discussion/287547/thread/8c2f3fdc/

**Comment by jeanlf** [comment]
now fixed, thanks for the reminder !

**Comment by megapro17** [comment]
Thank you so much! You're such a good expert!
