### ISSUE TITLE
LL-HLS: Playlist fetching might be too slow

### ISSUE THREAD

**Issue by DenizUgur** [gpac/gpac#2700]
We are trying to stream LL-HLS content with gpac following the guidelines at gpac's [wiki](https://github.com/gpac/gpac/wiki/LL-HLS).

Our gpac build is a recent commit 6493680a0f9763149f467240b4eeafbe83ccb504 in the master branch. The content produced from gpac is served over an H2/3 web server ([h20](https://github.com/h2o/h2o)). We have used the following command to produce the HLS files:

```bash
segment_duration="3" #seconds
chunk_duration="2" #seconds - 0.56 -> 14 frames for 25 fps video
publish_mode="br" #br: byte range, sf: seperate file

gpac flist:srcs=$source:floop=-1 reframer:rt=on \
  -o $manifest_file:rdirs=$output_dir:segdur=$segment_duration:cdur=$chunk_duration:profile=live:dmode=dynamic:llhls=br \
  -logs=dash@inf
```

We are testing our stream using HLS.js's demo [page](https://hlsjs.video-dev.org/demo/).

We observed in our experiments that the playlist fetching interval is calculated as follows:

```c
interval = max(segment_duration/2, chunk_duration)
 ```

For instance, let the segment duration be 10 seconds, then the manifest file is fetched every five seconds. So, even if the part duration is one second and the target latency is three seconds, the latency cannot be lower than five seconds. 
The playlist should be refetched for every part, right? Otherwise, the player will keep stalling.

Any comments? Are we missing something in our setup?

**Comment by jeanlf** [comment]
The scheduling in hls.js is out of our hands - my tests also seem to concur with your analysis, the playlist is not always reloaded fast enough to get the latest parts.

Adding `CAN-BLOCK-RELOAD` won't help much as we don't support this, it is likely to trigger either errors if the client really expects a new playlist, or in the best case a code 304.

During my experiments, I found out that we were not signaling the end of byte ranges soon enough which could cause hangups in clients, this is now fixed on master and may help a bit, but will not solve the hls.js scheduling issue. Maybe report this to the hls.js team ?

**Comment by acbegen** [comment]
Hi Jean,

> The scheduling in hls.js is out of our hands - my tests also seem to concur with your analysis, the playlist is not always reloaded fast enough to get the latest parts.

I think the problem is that the playlist is not refreshed fast enough. Even if we use separate parts (not byte ranges), the problem persists. The playlist needs to be updated so that the player can actually reload it and then get the latest part(s). Without the playlist running close to the live edge, there is nothing the ll-hls client can do.
 
> Adding `CAN-BLOCK-RELOAD` won't help much as we don't support this, it is likely to trigger either errors if the client really expects a new playlist, or in the best case a code 304.

Still, this is because the playlist is not being refreshed fast enough.
 
> During my experiments, I found out that we were not signaling the end of byte ranges soon enough which could cause hangups in clients, this is now fixed on master and may help a bit, but will not solve the hls.js scheduling issue. Maybe report this to the hls.js team ?

The playlist needs to be refreshed for every part (that is after every part). If the gpac server is not doing this, low latency won't be achieved (here low latency refers to three part duration).

**Comment by jeanlf** [comment]
In GPAC, LL-HLS parts are pushed in the playlist once the last byte of the part is written at the sink side. You can check this by running this simple script to diff the playlist every 500ms :
- replace URL to point  to variant playlist name
- use `gdate` instead of `date` on OSX

```
#!/bin/sh

file="test.m3u"
file2="test2.m3u"
echo "" > $file

for i in {1..100} ; do 
	echo "Playlist diff at date $(date +%T.%3N)"
	wget -O $file2 http://127.0.0.1:8080/live_1.m3u8 2>/dev/null
	diff $file $file2
	cp $file2  $file
	sleep 0.5
done
```

**Comment by acbegen** [comment]
> In GPAC, LL-HLS parts are pushed in the playlist once the last byte of the part is written at the sink side. You can check this by running this simple script to diff the playlist every 500ms :

The problem is the playlist is not updated after each part. We can try the latest master but ours is not that old IIRC. @DenizUgur can confirm. In our case, regardless of the part duration, the playlist is updated twice per segment (not for each part).

**Comment by jeanlf** [comment]
@DenizUgur in your script, I see:
> segment_duration="3" #seconds
> chunk_duration="2" #seconds - 0.56 -> 14 frames for 25 fps video

this is weird, since this would produce only 2 fragments (one of 2 sec, one of 1 sec) - is this intended ?

**Comment by zafergurel** [comment]
Hi @jeanlf,
We fetched the latest code (master branch) this time and are now running the latest gpac. The part duration is 0.2 second and the segment duration is 2 seconds. However the update interval seems to be 2 seconds.

You can see it yourself [here](https://hlsjs.video-dev.org/demo/?src=https%3A%2F%2Fll.streaming.university%2Fmain.m3u8&demoConfig=eyJlbmFibGVTdHJlYW1pbmciOnRydWUsImF1dG9SZWNvdmVyRXJyb3IiOnRydWUsInN0b3BPblN0YWxsIjpmYWxzZSwiZHVtcGZNUDQiOmZhbHNlLCJsZXZlbENhcHBpbmciOi0xLCJsaW1pdE1ldHJpY3MiOi0xfQ==).

**Comment by DenizUgur** [comment]
Could you try it again? Apparently the service shut down.

**Comment by jeanlf** [comment]
still down

**Comment by zafergurel** [comment]
We got it working again.

**Comment by jeanlf** [comment]
using the script below on your source, I can see the parts being pushed one at a time to the playlist, so like I said I believe the issue is from the playback side not fetching the playlist fast enough.


```
#!/bin/sh

url=https://ll.streaming.university/main_1.m3u8
#url=https://ll.streaming.university/main_2.m3u8
file="test.m3u"
file_2="test_2.m3u"
diffs=diffs.txt
echo "" > $file
echo "" > $diffs

for i in {1..100} ; do 
	str="Playlist diff at date $(gdate +%T.%3N)"
	echo $str
	wget -O $file_2 $url 2>/dev/null
	echo $str >> $diffs
	diff $file $file_2 >> $diffs
	echo '\n' >> $diffs
	cp $file_2  $file
done

```

**Comment by zafergurel** [comment]
Thanks for the script. It works as you mentioned. The issue may be related to the player.

**Comment by acbegen** [comment]
THEO's LL-HLS test player does not work either with the GPAC input. So, it kind of makes me think this is not just the player. hls.js works with Apple's LL-HLS tools just fine (so does THEO's player).
