### ISSUE TITLE
convert/dump an animated SVG to MP4

### ISSUE THREAD

**Issue by romangrothausmann** [gpac/gpac#543]
How can I convert/dump an animated SVG to MP4? 
MP4Client seems not to support dumping to MP4 and MP4Box does not seem to allow specification of the duration to dump. 
Is there any better way than to encode the raw AVI from MP4Client? 
Can MP4Client dump to STDOUT for piping?

Using the simple SVG from  #528, I tried using a fifo but both mencoder and ffmpeg yield a "running" image with changing color (even for other sizes like 101x1000):

```
MP4Client -no-audio -size 100x1000  -avi 0-10 -fps 25  all.dot.Make.asvg -out fifo.avi

ffmpeg -y -f rawvideo  -pix_fmt bgr24 -r 25 -s 100x1000  -i fifo.avi  file.mp4
mencoder -cache 8000 -nosound -o test.mp4  -ovc x264  -fps 25 -demuxer rawvideo -rawvideo w=100:h=1000:fps=25.000:format=bgr24 fifo.avi
```

**Comment by jeanlf** [comment]
use GPAC 0.9.0, see  https://github.com/gpac/gpac/wiki/olay-composition

**Comment by romangrothausmann** [comment]
Many thanks @jeanlf for the update. I tried to give it a try but must admit I'm a bit out-of-business concerning the rendering of animated SVGs and the use of gpac. I compiled gpac master (e7e5cbcea, as I could only find a tag for v0.8.0) and got `MP42TS`,  `MP4Box` and  `MP4Client`. However, the instruction on https://github.com/gpac/gpac/wiki/olay-composition seem to refer to `gpac` executable. Am I missing something here? What command line calls would I need to convert an animated SVG into an MP4 without dumping a RAW format?

**Comment by jeanlf** [comment]
0.9.0 is available in the filters branch, and installers are available [here](https://gpac.wp.imt.fr/downloads/gpac-filters-branch/)

For dumping into MP4 you will need to specify the desired codec and bitrate between the composition filter and the muxer:
```
gpac -i source.svg compositor @ enc:c=avc:b=1M @ -o dump.mp4
```

**Comment by romangrothausmann** [comment]
> 0.9.0 is available in the filters branch

Ah, thanks, got it. Local compilation did not work for me (`No rule to make target gpac "esi.h" needed by 'ietf/rtp_depacketizer.o'.  Stop.`), but it does within docker (https://gitlab.com/romangrothausmann/dfgpac).

> installers are available here

I was not able to satisfy the dependencies for neither `gpac_0.9.0-DEV-rev2687-g06b48108-filters_amd64.deb` nor `gpac_0.8.0-rev1-gc1990d5c-master_amd64.deb`, tried `ubuntu:14.04`, `ubuntu:16.04`, `ubuntu:18.04` and `ubuntu:18.10` (`Dependency is not satisfiable: libavcodec-ffmpeg56 (>= 7:2.4)|libavcodec-ffmpeg-extra56 (>= 7:2.4)`)
but `gpac_0.6.1_amd64.deb` works with `ubuntu:14.04` (https://gitlab.com/romangrothausmann/dfgpac/pipelines/78569248).

> For dumping into MP4 you will need to specify the desired codec and bitrate between the composition filter and the muxer

I see. So I tried `gpac -i test/test01.asvg compositor:fps=25:dur=5:osize=100x1000 @ enc:c=avc:b=1M @ -o test.mp4`, which works (https://gitlab.com/romangrothausmann/dfgpac/-/jobs/280915431) but the resulting MP4 (https://gitlab.com/romangrothausmann/dfgpac/-/jobs/280915431/artifacts/file/test.mp4) shows only the blobs but not their text. If dur=6 or greater, `gpac` never ends. This used to work with `MP4Client` (v0.8.0) compiled locally.

**Comment by romangrothausmann** [comment]
Restructured a bit to test `MP4Client` from v0.8.0. It compiles fine in docker (https://gitlab.com/romangrothausmann/dfgpac/pipelines/78586013) but SVG to AVI conversion fails (https://gitlab.com/romangrothausmann/dfgpac/-/jobs/280986654). I have the impression that `MP4Client` does not work without X even if on GUI is used.

**Comment by aureliendavid** [comment]
> Ah, thanks, got it. Local compilation did not work for me (`No rule to make target gpac "esi.h" needed by 'ietf/rtp_depacketizer.o'. Stop.`), but it does within docker (https://gitlab.com/romangrothausmann/dfgpac).
> 

There are build instructions here that should work on all recent debian/ubuntu : https://github.com/gpac/gpac/wiki/GPAC-Build-Guide-for-Linux


> I was not able to satisfy the dependencies for neither `gpac_0.9.0-DEV-rev2687-g06b48108-filters_amd64.deb` nor `gpac_0.8.0-rev1-gc1990d5c-master_amd64.deb`, tried `ubuntu:14.04`, `ubuntu:16.04`, `ubuntu:18.04` and `ubuntu:18.10` (`Dependency is not satisfiable: libavcodec-ffmpeg56 (>= 7:2.4)|libavcodec-ffmpeg-extra56 (>= 7:2.4)`)
> but `gpac_0.6.1_amd64.deb` works with `ubuntu:14.04` (https://gitlab.com/romangrothausmann/dfgpac/pipelines/78569248).
> 

The linux installers are made with/for ubuntu 16.04 so it should work. 

The missing package in your error message is here https://packages.ubuntu.com/xenial/libavcodec-ffmpeg56

Maybe you don't have the `universe` repo activated? Or something is conflicting with `libavcodec`?

**Comment by aureliendavid** [comment]
Also if you're switching between the `master` and `filters` branch in the same directory for building, you need to run `make distclean` before the `./configure && make` so that there's no confusion between targets.

**Comment by romangrothausmann** [comment]
Thanks @aureliendavid for your feedback.

> The linux installers are made with/for ubuntu 16.04 so it should work.

Yes, with ubuntu 16.04 it does, just took very long for gdebi to resolve all deps (https://gitlab.com/romangrothausmann/dfgpac/pipelines/78629163) but the actual rendering of the test SVG to AVI still does not work with `MP4Client`: https://gitlab.com/romangrothausmann/dfgpac/-/jobs/281172061
Is that expected without X?

**Comment by aureliendavid** [comment]
> Yes, with ubuntu 16.04 it does, just took very long for gdebi to resolve all deps (https://gitlab.com/romangrothausmann/dfgpac/pipelines/78629163) but the actual rendering of the test SVG to AVI still does not work with `MP4Client`: https://gitlab.com/romangrothausmann/dfgpac/-/jobs/281172061
> Is that expected without X?

hm yes I don't think it will run without X, however if you don't want to install a full X server, it should work with a virtual framebuffer like Xvfb (see http://elementalselenium.com/tips/38-headless for example)

that being said I think it would be better to try to make it work with the filters branch and gpac tool ; and if it doesn't work properly, upload the source svg and command line so we can try to debug the issue

**Comment by jeanlf** [comment]
the duration issue is now fixed when dumping with 0.9.0, thanks for the report. I'll have a look at the text issue

**Comment by jeanlf** [comment]
The text works properly with 0.9.0, however the configuration file for the font has changed between 0.8.0 and 0.9.0. You need to remove the GPAC config file ($HOME/.gpac/GPAC.cfg) or launch at least once the MP4Client or the compositor with rescan-font set:
```
MP4Client -rescan-fonts source.svg
gpac -i source.svg compositor @ vout -rescan-fonts
```
 or simply change the rescan font option in the config file: `[core]rescan-fonts=yes`.

I will try to automate this process ...

**Comment by romangrothausmann** [comment]
> the duration issue is now fixed when dumping with 0.9.0, thanks for the report. 

Thanks @jeanlf for fixing that, works well now:
https://gitlab.com/romangrothausmann/dfgpac/pipelines/78839166

**Comment by romangrothausmann** [comment]
> The text works properly with 0.9.0, however the configuration file for the font has changed between 0.8.0 and 0.9.0. You need to remove the GPAC config file ($HOME/.gpac/GPAC.cfg) 

Hm, not sure if that is the problem since there is no `GPAC.cfg` in the plain install in the docker image. However I get one with (https://gitlab.com/romangrothausmann/dfgpac/commit/d1ab2339a7d72c72a85babd0d25cbf9772397536)
`gpac -i test01.asvg compositor @ vout -rescan-fonts`
but the text is still missing in the MP4 (https://gitlab.com/romangrothausmann/dfgpac/-/jobs/281978346/artifacts/browse). Is the config (https://gitlab.com/romangrothausmann/dfgpac/-/jobs/281978346) OK?

**Comment by romangrothausmann** [comment]
The rendered SVG in the resulting MP4 shows some kind of "jump" of the border lines for the node-ellipsoids when transitioning from some transparency to fully opaque. It looks to me a bit like the anti-aliasing is different between fully opaque and not fully opaque. Is that expected?

**Comment by jeanlf** [comment]
Regarding text & config file, it seems OK. Could you try adding `-logs=compose@debug` and post the results/check the text node is drawn ?

Regarding opacity, the anti-aliasing algo is the same regardless of the opacity attribute. However, group opacity is handled by rasterizing to an offscreen surface and then blitting with alpha the surface to the main canvas, which differs from direct rendering on the main canvas due to chosen blitter, pixel alignment and potential scaling involved. This is the "expected behaviour" given the code, but this could be further optimized. Note you won't have this issue for opacity on a graphical primitive such as rect or text, because no intermediate rendering is used.
